name: Terraform CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      YC_SERVICE_ACCOUNT_KEY_FILE: ${{ github.workspace }}/.key.json
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ru-central1

    steps:
      - uses: actions/checkout@v4

      - name: Write Yandex SA key to file
        env:
          SA_JSON: ${{ secrets.YC_SA_JSON }}
        run: |
          echo "$SA_JSON" > .key.json
          chmod 600 .key.json

      - name: Write backend config from secret
        env:
          BACKEND: ${{ secrets.BACKEND }}
        run: |
          echo "$BACKEND" > backend-config.hcl

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.7"

      - name: Terraform
        run: |
          terraform init -input=false -backend-config=backend-config.hcl
          terraform validate
          terraform plan -input=false -no-color